server:
  port: 8080

spring:
  application:
    name: credit-application-service

  datasource:
    url: jdbc:postgresql://localhost:5432/coopcredit_db
    username: coopcredit_user
    password: coopcredit_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 10
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 10

  flyway:
    enabled: true
    locations: classpath:db/migration

# -----------------------------------------------------------------------------
# CONFIGURACIÓN DE SEGURIDAD Y JWT (Claves Propias)
# -----------------------------------------------------------------------------
app:
  jwt-secret: 92a016aa43f9e825cfa20615ada5ce6ff3d89266781168d13f98b108241a0a76
  jwt-expiration-milliseconds: 3600000

# -----------------------------------------------------------------------------
# INTEGRACIÓN REST (risk-central-mock-service)
# -----------------------------------------------------------------------------
risk-central:
  service:
    url: http://localhost:8081/api/v1

# -----------------------------------------------------------------------------
# 7. CONFIGURACIÓN DE OBSERVABILIDAD (ACTUATOR / MICROMETER)
# -----------------------------------------------------------------------------
management:
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus